(function(){window.BindIt={}}).call(this);(function(){BindIt.Logger=console}).call(this);
(function(){var b;b=function(){function b(){this.keys=[];this.values=[];Object.defineProperty(this,"length",{get:function(){return this.keys.length}})}b.prototype.add=function(b,e){var c;c=this.keys.indexOf(b);if(0>c)this.keys.push(b),this.values.push(e);else return this.values[c]=e};b.prototype.remove=function(b){b=this.keys.indexOf(b);if(!(0>b))return this.keys.splice(b,1),this.values.splice(b,1)};b.prototype.clear=function(){this.keys.length=0;return this.values.length=0};b.prototype.get=function(b){b=
this.keys.indexOf(b);return this.values[b]};b.prototype.getKeyByValue=function(b){b=this.values.indexOf(b);return this.keys[b]};b.prototype.length=function(){return this.keys.length};return b}();BindIt.Hash=b}).call(this);
(function(){var b;b=function(){function b(){this.eventHandlers={}}b.prototype.addEventListener=function(b,e){null==this.eventHandlers[b]&&(this.eventHandlers[b]=[]);return this.eventHandlers[b].push(e)};b.prototype.removeEventListener=function(b,e){var c;if(null!=this.eventHandlers[b]&&(c=this.eventHandlers[b].indexOf(e),!(0>c)))return this.eventHandlers[b].splice(c,1)};b.prototype.callEvent=function(b,e){var c,a,d,l,r;if(null!=this.eventHandlers[b]){l=this.eventHandlers[b];r=[];a=0;for(d=l.length;a<
d;a++)c=l[a],r.push(c.apply(this,e));return r}};return b}();window.BindIt.EventDispatcher=b}).call(this);
(function(){var b,f,k,e={}.hasOwnProperty,c=function(a,d){function l(){this.constructor=a}for(var c in d)e.call(d,c)&&(a[c]=d[c]);l.prototype=d.prototype;a.prototype=new l;a.__super__=d.prototype;return a};b=function(a){function d(a,c){var b;this.source=a;null==this.source&&(this.source={});if(this.source instanceof d)return this.source;if(null!=this.source.__bindit_model)return this.source.__bindit_model;if(this.source instanceof Array&&!0!==c)return new BindIt.ModelArray(this.source);d.__super__.constructor.call(this);
Object.defineProperty(this.source,"__bindit_model",{get:function(){return this}.bind(this),enumerable:!1});if(!(this.source instanceof Array))for(b in this.source)k(this,b)}c(d,a);d.prototype.getSource=function(){return this.source};return d}(BindIt.EventDispatcher);f=function(a){return null==a?null:a instanceof Object?new b(a):a};k=function(a,d){if(!a.hasOwnProperty(d))return Object.defineProperty(a,d,{get:function(){var l;l=a.getSource()[d];if(null==l)return null;if(l instanceof Function)return l.bind(a);
l instanceof Object&&(l=new b(l));return l},set:function(l){var c,q;c=a.getSource();q=c[d];l instanceof b&&(l=l.getSource());if(q!==l)return c[d]=l,this.callEvent(b.Events.VALUE_CHANGED,[a,d,f(q),f(l)])},enumerable:!0})};b.processProperty=k;b.Events={VALUE_CHANGED:"value_changed",ARRAY_CHANGED:"array_changed"};window.BindIt.Model=b;window.BindIt.getModel=f;window.BindIt.getSource=function(a){return null==a?null:a instanceof b?a.getSource():a}}).call(this);
(function(){var b,f,k={}.hasOwnProperty,e=function(c,a){function d(){this.constructor=c}for(var l in a)k.call(a,l)&&(c[l]=a[l]);d.prototype=a.prototype;c.prototype=new d;c.__super__=a.prototype;return c};BindIt.Model.ArrayEvents={INSERTED:"inserted",REMOVED:"removed",APOCALYPTIC:"apocalyptic"};b=function(c){function a(d,l){this.source=d;a.__super__.constructor.call(this,this.source,!0);BindIt.Model.processProperty(this,"length");this.source.selectedItem=0;BindIt.Model.processProperty(this,"selectedItem");
null==l&&(l=!0);!0===l&&(this.source.selectedItems=0,BindIt.Model.processProperty(this,"selectedItems"),this.selectedItems=new BindIt.ModelArray([],!1));f(this);this.addEventListener(BindIt.Model.Events.VALUE_CHANGED,function(d,a,l,c){if("length"===a&&!(l>c))return f(d)})}e(a,c);a.prototype.push=function(d){var a;a=this.getSource().push(BindIt.getSource(d));f(this);this.callEvent(BindIt.Model.Events.ARRAY_CHANGED,[this,BindIt.Model.ArrayEvents.INSERTED,this.getSource().length-1,BindIt.getModel(d)]);
return BindIt.getModel(a)};a.prototype.pop=function(){var d;d=this.getSource().pop();this.callEvent(BindIt.Model.Events.ARRAY_CHANGED,[this,BindIt.Model.ArrayEvents.REMOVED,this.getSource().length,BindIt.getModel(d)]);return BindIt.getModel(d)};a.prototype.concat=function(d){return new BindIt.Model(this.getSource().concat(d))};a.prototype.join=function(d){return this.getSource().join(d)};a.prototype.reverse=function(){var d;d=this.getSource().reverse();this.callEvent(BindIt.Model.Events.ARRAY_CHANGED,
[this,BindIt.Model.ArrayEvents.APOCALYPTIC]);return BindIt.getModel(d)};a.prototype.shift=function(){var d;d=this.getSource().shift();this.callEvent(BindIt.Model.Events.ARRAY_CHANGED,[this,BindIt.Model.ArrayEvents.REMOVED,0,BindIt.getModel(d)]);return BindIt.getModel(d)};a.prototype.slice=function(){return new BindIt.Model(this.getSource().slice.apply(this.getSource(),arguments))};a.prototype.sort=function(){var d;d=this.getSource().sort.apply(this.getSource(),arguments);this.callEvent(BindIt.Model.Events.ARRAY_CHANGED,
[this,BindIt.Model.ArrayEvents.APOCALYPTIC]);return BindIt.getModel(d)};a.prototype.splice=function(){var d;d=this.getSource().splice.apply(this.getSource(),arguments);this.callEvent(BindIt.Model.Events.ARRAY_CHANGED,[this,BindIt.Model.ArrayEvents.APOCALYPTIC]);return BindIt.getModel(d)};a.prototype.unshift=function(d){var a;a=this.getSource().unshift(BindIt.getSource(d));this.callEvent(BindIt.Model.Events.ARRAY_CHANGED,[this,BindIt.Model.ArrayEvents.INSERTED,0,BindIt.getModel(d)]);return BindIt.getModel(a)};
a.prototype.indexOf=function(d){return this.getSource().indexOf(BindIt.getSource(d))};return a}(BindIt.Model);f=function(c){var a,d,l,b;b=[];a=d=0;for(l=c.length-1;0<=l?d<=l:d>=l;a=0<=l?++d:--d)b.push(BindIt.Model.processProperty(c,a));return b};window.BindIt.ModelArray=b}).call(this);
(function(){var b,f={}.hasOwnProperty,k=function(b,c){function a(){this.constructor=b}for(var d in c)f.call(c,d)&&(b[d]=c[d]);a.prototype=c.prototype;b.prototype=new a;b.__super__=c.prototype;return b};b=function(b){function c(a){var d=this;this.element=a;c.__super__.constructor.call(this);BindIt.DOM.addEventHandler(this.element,"click",function(){return d.callEvent("click",arguments)})}k(c,b);c.prototype.click=function(a){return this.addEventListener("click",a)};return c}(BindIt.EventDispatcher);
BindIt.DOMEventDispatcher=b}).call(this);
(function(){var b,f=function(c,a){return function(){return c.apply(a,arguments)}},k={}.hasOwnProperty,e=function(c,a){function d(){this.constructor=c}for(var l in a)k.call(a,l)&&(c[l]=a[l]);d.prototype=a.prototype;c.prototype=new d;c.__super__=a.prototype;return c};BindIt.DATA_BIND_ATTRIBUTE="data-bind";BindIt.FORM_BIND_ATTRIBUTE="form-bind";b=function(c){function a(d){this.element=d;this.modelArrayHandler=f(this.modelArrayHandler,this);this.modelHandler=f(this.modelHandler,this);if(null!=this.element.__bindit_view)throw Error("Element should have only one view");
a.__super__.constructor.call(this,this.element);d.__bindit_view=this;this.subscribes=[];this.refreshSubscribes()}e(a,c);a.prototype.getValue=function(d,a){var c;null==a&&(a=this.getModelPath());if(null==a||0===a.length)return null;try{c=eval(a.shift())}catch(b){}for(;0<a.length;){if(null==c)return null;c instanceof BindIt.ModelArray&&(c=c[c.selectedItem]);null!=c&&(c=c[a.shift()])}c instanceof BindIt.ModelArray&&!0!==d&&(c=c[c.selectedItem]);return c};a.prototype.setValue=function(d){var a,c;a=this.getModelPath();
null==a&&(a=[]);for(c=window;1<a.length;){if(null==c)return;c instanceof BindIt.ModelArray&&(c=c[c.selectedItem]);if(null==c)return;c=c[a.shift()]}if(null!=c&&(c instanceof BindIt.ModelArray&&(c=c[c.selectedItem]),null!=c))return c[a[0]]=d};a.prototype.callBindFunction=function(){var d,a,c;a=this.getModelPath();null==a&&(a=[]);c=null;for(d=window;0<a.length&&null!=d;){d instanceof BindIt.ModelArray&&(c=d,d=d[d.selectedItem]);if(null==d)break;c=d;d=d[a.shift()]}if(null!=d&&d instanceof Function)return d.apply(c,
arguments)};a.prototype.getModelPath=function(d){var a;null==d&&(d=this.element.getAttribute(BindIt.DATA_BIND_ATTRIBUTE));if(null==d)return null;for(a=this.element.parentNode;null!==a;)null!=a.hasAttribute&&a.hasAttribute(BindIt.FORM_BIND_ATTRIBUTE)&&(d=""+a.getAttribute(BindIt.FORM_BIND_ATTRIBUTE)+":"+d),a=a.parentNode;return d.split(":")};a.prototype.modelHandler=function(d,a,c,b){this.refreshSubscribes();return"function"===typeof this.changed?this.changed(this,d,BindIt.Model.Events.VALUE_CHANGED,
a,c,b):void 0};a.prototype.modelArrayHandler=function(d,a,c,b){this.refreshSubscribes();return"function"===typeof this.changed?this.changed(this,d,BindIt.Model.Events.ARRAY_CHANGED,a,c,b):void 0};a.prototype.refreshSubscribes=function(){var d,a,c,b,n,g,e;c=[];c.push(this.getModelPath());a=this.getExtraModels();if(null!=a)for(b=0,n=a.length;b<n;b++)d=a[b],d=this.getModelPath(d),null!=d&&c.push(d);a=[];d=0;for(g=c.length;d<g;d++){n=c[d];null==n&&(n=[]);for(b=window;0<n.length&&null!=b;){b instanceof
BindIt.ModelArray&&(b=b[b.selectedItem],b instanceof BindIt.Model&&a.push(b));if(null==b)break;b=b[n.shift()];b instanceof BindIt.Model&&a.push(b)}this.fillSubscribes(b,a,!1)}b=[];n=[];d=0;for(g=a.length;d<g;d++)c=a[d],0>this.subscribes.indexOf(c)&&n.push(c);e=this.subscribes;d=0;for(g=e.length;d<g;d++)c=e[d],0>a.indexOf(c)&&b.push(c);g=0;for(d=n.length;g<d;g++)c=n[g],c.addEventListener(BindIt.Model.Events.VALUE_CHANGED,this.modelHandler),c instanceof BindIt.ModelArray&&c.addEventListener(BindIt.Model.Events.ARRAY_CHANGED,
this.modelArrayHandler);d=0;for(n=b.length;d<n;d++)c=b[d],c.removeEventListener(BindIt.Model.Events.VALUE_CHANGED,this.modelHandler),c instanceof BindIt.ModelArray&&c.removeEventListener(BindIt.Model.Events.ARRAY_CHANGED,this.modelArrayHandler);return this.subscribes=a};a.prototype.fillSubscribes=function(d,a,c){var b,n;if(null!=d&&d instanceof BindIt.Model&&!(0<=a.indexOf(d)&&c))if(0>a.indexOf(d)&&a.push(d),d instanceof BindIt.ModelArray)for(this.fillSubscribes(d.selectedItems,a,!0),c=0,n=d.length;c<
n;c++)b=d[c],this.fillSubscribes(b,a,!0);else{c=[];for(b in d)c.push(this.fillSubscribes(d[b],a,!0));return c}};a.prototype.getExtraModels=function(){return null};return a}(BindIt.DOMEventDispatcher);BindIt.View=b}).call(this);
(function(){var b,f,k,e;BindIt.VIEW_ATTRIBUTE="view";f=function(c){var a;a=c.getAttribute(BindIt.VIEW_ATTRIBUTE);null==a&&(a=BindIt.View.Default[c.tagName.toLowerCase()]);null==a&&(a="BindIt.View");c=BindIt.View;try{c=eval(a)}catch(d){}return c};b=function(c){var a;if(null!=c&&(null==c.__bindit_view&&null!=c.getAttribute)&&(a=c.getAttribute(BindIt.DATA_BIND_ATTRIBUTE),null!=a))return new (f(c))(c)};e=function(c){var a,d,l,r;b(c);if(null!=c.getElementsByTagName){a=c.getElementsByTagName("*");r=[];
d=0;for(l=a.length;d<l;d++)c=a[d],r.push(b(c));return r}};BindIt.DOM={getViewClass:f,createView:b,processElement:e,addEventHandler:function(c,a,d){if(null!=d&&null!=c.addEventListener)return c.addEventListener(a,d)}};BindIt.View.Default={};k=function(){return e(document)};(function(){BindIt.DOM.addEventHandler(window,"load",k);return BindIt.DOM.addEventHandler(window,"DOMSubtreeModified",function(c){return e(c.target)})})()}).call(this);
(function(){var b,f,k,e,c,a=function(d,a){return function(){return d.apply(a,arguments)}};b=function(){function d(c){this.template=c;this.create=a(this.create,this);if(this.template instanceof d)return this.template}d.prototype.create=function(){var d;d=c(this,this.template.tag,arguments);d=null!=d?document.createElement(d):document.createDocumentFragment();k(this,d,arguments);e(this,d,arguments);return d};return d}();k=function(d,a,r){var q,n,g,e,f;n=d.template.attributes;null==n&&(n={});n=c(d,n,
r);f=b.OftenAttributes;g=0;for(e=f.length;g<e;g++)q=f[g],null!=d.template[q]&&(n[q]=d.template[q]);g=[];for(q in n)d=n[q],d=c(this,d,r),g.push(a.setAttribute(q,d));return g};e=function(d,a,b){var q,n,e,m,p;n=c(d,d.template.html,b);e=c(d,d.template.text,b);q=c(d,d.template.child,b);if(1<(null!=n?1:0)+(null!=e?1:0)+(null!=q?1:0))throw Error("Template exception. Only one available: html, text, child");null!=n&&(a.innerHTML=n);null!=e&&(a.innerText=e);if(null!=q){p=[];e=0;for(m=q.length;e<m;e++)n=q[e],
p.push(f(d,a,n,b));return p}};f=function(d,a,c,q){var e,g;e=c;e instanceof Function&&(e=e.apply(d,q));if("string"===typeof e)return a.appendChild(document.createTextNode(e));if(e instanceof Node&&(null!=c[b.TEMPLATE_ID_PROPERTY]&&(a[c[b.TEMPLATE_ID_PROPERTY]]=c),e instanceof Node))return a.appendChild(c);if(e instanceof Object)return d=new b(e),null!=d[b.TEMPLATE_ID_PROPERTY]&&(g=d[b.TEMPLATE_ID_PROPERTY]),null!=d.template[b.TEMPLATE_ID_PROPERTY]&&null==g&&(g=d.template[b.TEMPLATE_ID_PROPERTY]),q=
d.create.apply(e,q),null!=g&&(a[g]=q),a.appendChild(q)};c=function(d,a,c){var b;b=a;a instanceof Function&&(b=a.apply(d,c));return b};b.OftenAttributes=["id","name","class","style","src","href","value",BindIt.DATA_BIND_ATTRIBUTE,BindIt.VIEW_ATTRIBUTE,"item-view","type","form-bind"];b.TEMPLATE_ID_PROPERTY="template-id";BindIt.Template=b}).call(this);
(function(){var b,f,k={}.hasOwnProperty,e=function(c,a){function d(){this.constructor=c}for(var b in a)k.call(a,b)&&(c[b]=a[b]);d.prototype=a.prototype;c.prototype=new d;c.__super__=a.prototype;return c};b=function(c){function a(d){var c;this.element=d;a.__super__.constructor.call(this,this.element);this.itemsSubscribes=new BindIt.Hash;this.itemsElements=[];this.calculateItemView();null!=this.itemView&&("function"===typeof(c=this.itemView).init&&c.init(this),this.changed())}e(a,c);a.prototype.changed=
function(d,a,c,b,e,g){this.callChanged(a,c,c===BindIt.Model.Events.VALUE_CHANGED?null:b,c===BindIt.Model.Events.VALUE_CHANGED?null:e,c===BindIt.Model.Events.VALUE_CHANGED?b:null,c===BindIt.Model.Events.VALUE_CHANGED?e:null,g);return this.refreshItemsSubscribes()};a.prototype.callChanged=function(d,a,c,b,e,g,m){var p,k,h;h=this.getValue(!0);if(null!=h){p=this.itemsSubscribes.get(d);c!==BindIt.Model.ArrayEvents.INSERTED&&c!==BindIt.Model.ArrayEvents.REMOVED&&(b=h.indexOf(p));k=this.itemsElements[b];
if(null!=p&&null!=k&&(b=h.indexOf(p),null!=p&&null!=k))return this.itemView.changed(k,h,b,h.selectedItem===b,0<=h.selectedItems.indexOf(b));if(d===h&&a===BindIt.Model.Events.VALUE_CHANGED){if("length"===e){if(g<m)for(b=h=g,p=m-1;g<=p?h<=p:h>=p;b=g<=p?++h:--h)m=this.createItemElement(d,b),null!=m&&this.element.appendChild(m);else{for(;null!=this.element.childNodes[m];)h=this.element.childNodes[this.element.childNodes.length-1],this.element.removeChild(h);this.itemsElements.length=m}return}if("selectedItem"===
e){this.itemView.changed(this.itemsElements[g],h,g,!1,0<=h.selectedItems.indexOf(g));this.itemView.changed(this.itemsElements[m],h,m,!0,0<=h.selectedItems.indexOf(g));return}if("selectedItems"===e){d=[];b=0;for(a=g.length;b<a;b++)p=g[b],d.push(p);b=0;for(g=m.length;b<g;b++)p=m[b],d.push(p);if(0<d.length)for(b=m=0,d=d.length-1;0<=d?m<=d:m>=d;b=0<=d?++m:--m)this.itemView.changed(this.itemsElements[b],h,b,b===h.selectedItem,0<=h.selectedItems.indexOf(b));return}if(f(e)&&(b=parseInt(e),k=this.itemsElements[b],
null!=m&&null!=k))return this.itemView.changed(k,h,b,h.selectedItem===b,0<=h.selectedItems.indexOf(b))}if(d===h.selectedItems){if(c===BindIt.Model.ArrayEvents.INSERTED){k=this.itemsElements[m];this.itemView.changed(k,h,m,h.selectedItem===m,0<=h.selectedItems.indexOf(m));return}if(c===BindIt.Model.ArrayEvents.REMOVED){k=this.itemsElements[m];this.itemView.changed(k,h,m,h.selectedItem===m,0<=h.selectedItems.indexOf(m));return}if(a===BindIt.Model.Events.VALUE_CHANGED&&f(e)){this.itemView.changed(this.itemsElements[g],
h,g,h.selectedItem===g,0<=h.selectedItems.indexOf(g));this.itemView.changed(this.itemsElements[m],h,m,h.selectedItem===m,0<=h.selectedItems.indexOf(m));return}}if(d===h&&c===BindIt.Model.ArrayEvents.INSERTED){m=this.createItemElement(d,b);if(null==m)return;if(h.length>b+1)for(g=p=a=b+1,c=h.length-1;a<=c?p<=c:p>=c;g=a<=c?++p:--p)this.itemView.changed(this.itemsElements[g],h,g,h.selectedItem===g,0<=h.selectedItems.indexOf(g));return b===d.length-1?this.element.appendChild(m):this.element.insertBefore(m,
this.element.childNodes[b])}if(d===h&&c===BindIt.Model.ArrayEvents.REMOVED){this.itemsElements.splice(b,1);if(h.length>b)for(g=d=m=b,p=h.length-1;m<=p?d<=p:d>=p;g=m<=p?++d:--d)this.itemView.changed(this.itemsElements[g],h,g,h.selectedItem===g,0<=h.selectedItems.indexOf(g));return this.element.removeChild(this.element.childNodes[b])}return this.apocalyptic()}};a.prototype.calculateItemView=function(){var d;if(this.element.hasAttribute(a.ITEM_VIEW_ATTRIBUTE)){d=this.element.getAttribute(a.ITEM_VIEW_ATTRIBUTE);
try{this.itemView=eval(d)}catch(c){BindIt.Logger.warn("BindIt.View.ListView: invalid '"+a.ITEM_VIEW_ATTRIBUTE+"' attribute",this.element);return}if(null==this.itemView)return BindIt.Logger.warn("BindIt.View.ListView: invalid '"+a.ITEM_VIEW_ATTRIBUTE+"' attribute",this.element)}else BindIt.Logger.warn("BindIt.View.ListView: element hasn't '"+a.ITEM_VIEW_ATTRIBUTE+"' attribute",this.element)};a.prototype.apocalyptic=function(){for(var d,a,c,b,e;null!=this.element.firstChild;)this.element.removeChild(this.element.firstChild);
this.itemsElements=[];c=this.getValue(!0);if(null!=c){a=document.createDocumentFragment();if(0<c.length)for(d=b=0,e=c.length-1;0<=e?b<=e:b>=e;d=0<=e?++b:--b)d=this.createItemElement(c,d),null!=d&&a.appendChild(d);return this.element.appendChild(a)}};a.prototype.createItemElement=function(a,c){var b;if(null!=this.itemView)return b=this.itemView.create(a,c,a.selectedItem===c,0<=a.selectedItems.indexOf(c)),this.itemsElements.splice(c,0,b),b};a.prototype.refreshItemsSubscribes=function(){var a,c,b,e,
f,g,m;e=this.getValue(!0);if(null!=e){this.itemsSubscribes.clear();m=[];f=0;for(g=e.length;f<g;f++)a=e[f],null!=a?(b=[],this.fillSubscribes(a,b,!0),m.push(function(){var e,g,f;f=[];e=0;for(g=b.length;e<g;e++)c=b[e],f.push(this.itemsSubscribes.add(c,a));return f}.call(this))):m.push(void 0);return m}};return a}(BindIt.View);f=function(c){return parseInt(c)===c};b.ITEM_VIEW_ATTRIBUTE="item-view";BindIt.View.List=b}).call(this);
(function(){var b,f={}.hasOwnProperty,k=function(b,c){function a(){this.constructor=b}for(var d in c)f.call(c,d)&&(b[d]=c[d]);a.prototype=c.prototype;b.prototype=new a;b.__super__=c.prototype;return b};b=function(b){function c(a){var d;this.element=a;d=this.element.getAttribute("type")||"undefined";a=c.byType[d.toLowerCase()];if(null!=a&&a instanceof Function)return new a(this.element);BindIt.Logger.warn("Can't find view class for input tag with type '"+d+"'",this.element)}k(c,b);return c}(BindIt.View);
b.byType={};BindIt.View.Input=b;BindIt.View.Default.input=b}).call(this);
(function(){var b,f={}.hasOwnProperty,k=function(b,c){function a(){this.constructor=b}for(var d in c)f.call(c,d)&&(b[d]=c[d]);a.prototype=c.prototype;b.prototype=new a;b.__super__=c.prototype;return b};b=function(b){function c(a){var d=this;this.element=a;c.__super__.constructor.call(this,this.element);this.setEnabled(this.getValue(!1));this.click(function(){var a;a=d.getValue(!1);if(d.getEnabled(a)){if(a instanceof Function)return d.callBindFunction();if(a.call instanceof Function)return a.call.apply(a)}})}
k(c,b);c.prototype.changed=function(){return this.setEnabled(this.getValue(!1))};c.prototype.setEnabled=function(a){return this.getEnabled(a)?this.element.removeAttribute("disabled"):this.element.setAttribute("disabled","disabled")};c.prototype.getEnabled=function(a){var d;if(null===a)return!1;if(a instanceof Function)return!0;a instanceof Object&&(d=a.enabled);d instanceof Function&&(d=d.apply(a));return!0===d&&(a instanceof Function||a.call instanceof Function)};return c}(BindIt.View);BindIt.View.Button=
b;BindIt.View.Default.button=b;BindIt.View.Default.a=b;BindIt.View.Input.byType.button=b}).call(this);
(function(){var b,f=function(c,a){return function(){return c.apply(a,arguments)}},k={}.hasOwnProperty,e=function(c,a){function d(){this.constructor=c}for(var b in a)k.call(a,b)&&(c[b]=a[b]);d.prototype=a.prototype;c.prototype=new d;c.__super__=a.prototype;return c};b=function(c){function a(d){this.element=d;this.calculateEvent=f(this.calculateEvent,this);this.elementListener=f(this.elementListener,this);this.keyup=f(this.keyup,this);a.__super__.constructor.call(this,this.element);this.changed();this.calculateEvent("enter");
this.calculateEvent("esc");this.element.onchange=this.elementListener;this.element.onkeyup=this.keyup;this.element.onpaste=this.elementListener}e(a,c);a.prototype.changed=function(){this.setEnabled();return this.setElementValue(this.getValue())};a.prototype.setEnabled=function(){return null!=this.getValue()?this.element.removeAttribute("disabled"):this.element.setAttribute("disabled","disabled")};a.prototype.setElementValue=function(a){a=a||"";if(this.element.value!==a)return this.element.value=a};
a.prototype.keyup=function(a){this.elementListener();13===a.keyCode&&"function"===typeof this.enter&&this.enter(a);if(27===a.keyCode)return"function"===typeof this.esc?this.esc(a):void 0};a.prototype.elementListener=function(){if(this.element.value!==this.getValue())return this.setValue(this.element.value)};a.prototype.calculateEvent=function(a){var c,b,e,f,g=this;if(this.element.hasAttribute(a)){f=this.element.getAttribute(a);c=f.lastIndexOf(".");c=0>c?"window":c=f.substr(0,c);try{return b=eval(f),
e=eval(c),this[a]=function(a){if(null!=b&&b instanceof Function)return b.apply(e,[g,a])}}catch(m){}}};return a}(BindIt.View);BindIt.View.Text=b;BindIt.View.Default.textarea=b;BindIt.View.Input.byType.text=b;BindIt.View.Input.byType.password=b;BindIt.View.Input.byType.hidden=b;BindIt.View.Input.byType.email=b;BindIt.View.Input.byType.search=b;BindIt.View.Input.byType.tel=b;BindIt.View.Input.byType.color=b;BindIt.View.Input.byType.range=b;BindIt.View.Input.byType.number=b;BindIt.View.Input.byType.url=
b;BindIt.View.Input.byType.time=b;BindIt.View.Input.byType.month=b;BindIt.View.Input.byType.week=b;BindIt.View.Input.byType.date=b;BindIt.View.Input.byType.datetime=b;BindIt.View.Input.byType["datetime-local"]=b}).call(this);
(function(){var b,f={}.hasOwnProperty,k=function(b,c){function a(){this.constructor=b}for(var d in c)f.call(c,d)&&(b[d]=c[d]);a.prototype=c.prototype;b.prototype=new a;b.__super__=c.prototype;return b};b=function(b){function c(a){c.__super__.constructor.call(this,a);this.subscribe();this.changed()}k(c,b);c.prototype.changed=function(){this.setElementValue(!0===this.getValue());return this.setElementEnabled(!0===this.getValue()||!1===this.getValue())};c.prototype.subscribe=function(){var a=this;return this.element.onchange=
function(){return a.setValue(a.getElementValue())}};c.prototype.getElementValue=function(){return this.element.checked};c.prototype.setElementValue=function(a){return this.element.checked=a};c.prototype.setElementEnabled=function(a){return a?this.element.removeAttribute("disabled"):this.element.setAttribute("disabled","")};return c}(BindIt.View);BindIt.View.Checkbox=b;BindIt.View.Input.byType.checkbox=b}).call(this);
(function(){var b,f,k={}.hasOwnProperty,e=function(c,a){function d(){this.constructor=c}for(var b in a)k.call(a,b)&&(c[b]=a[b]);d.prototype=a.prototype;c.prototype=new d;c.__super__=a.prototype;return c};f=function(){function c(){}c.prototype.init=function(a){return a.element.onchange=function(){var d;d=a.getValue(!0);if(null!=d)return d.selectedItem=parseInt(a.element.value)}};c.prototype.create=function(a,d,c){var b;b=document.createElement("option");b.innerHTML=a[d];b.setAttribute("value",d);this.setSelected(b,
a,d,c);return b};c.prototype.changed=function(a,d,c,b){a.innerHTML=d[c];return this.setSelected(a,d,c,b)};c.prototype.setSelected=function(a,c,b,e){return e?a.setAttribute("selected",""):a.removeAttribute("selected")};return c}();f.instance=new f;b=function(c){function a(c){this.element=c;a.__super__.constructor.call(this,this.element)}e(a,c);a.prototype.calculateItemView=function(){return this.itemView=f.instance};return a}(BindIt.View.List);b.ItemView=f;BindIt.View.Select=b;BindIt.View.Default.select=
b}).call(this);
(function(){var b,f={}.hasOwnProperty,k=function(b,c){function a(){this.constructor=b}for(var d in c)f.call(c,d)&&(b[d]=c[d]);a.prototype=c.prototype;b.prototype=new a;b.__super__=c.prototype;return b};b=function(b){function c(a){var b=this;this.element=a;c.__super__.constructor.call(this,this.element);this.element.onchange=function(){return b.setValue(b.element.getAttribute(c.VALUE_ATTRIBUTE))};this.changed()}k(c,b);c.prototype.changed=function(){var a,b;b=this.getValue(!1);a=this.element.getAttribute(c.VALUE_ATTRIBUTE);this.setElementEnabled(null!=
b);return this.setElementChecked(b===a)};c.prototype.setElementEnabled=function(a){return a?this.element.removeAttribute("disabled"):this.element.setAttribute("disabled","")};c.prototype.setElementChecked=function(a){return a?this.element.setAttribute("checked",""):this.element.removeAttribute("checked")};return c}(BindIt.View);b.VALUE_ATTRIBUTE="value";BindIt.View.Radio=b;BindIt.View.Input.byType.radio=b}).call(this);
(function(){var b,f,k={}.hasOwnProperty,e=function(b,a){function d(){this.constructor=b}for(var e in a)k.call(a,e)&&(b[e]=a[e]);d.prototype=a.prototype;b.prototype=new d;b.__super__=a.prototype;return b};f=function(){function c(a){this.view=a}c.prototype.init=function(a){return a.element.onchange=function(){var b;b=a.getValue(!0);if(null!=b)return b.selectedItem=parseInt(a.element.value)}};c.prototype.create=function(a,b){var c;c=document.createElement("option");this.initElement(c,a,b);return c};
c.prototype.changed=function(a,b,c,e){return this.initElement(a,b,c)};c.prototype.initElement=function(a,c,e){var f,k;try{f=this.view.getValue(!1,this.view.getModelPath(this.view.element.getAttribute(b.TO_ATTRIBUTE)))}catch(n){}k=this.getValue(a,c,e);a.setAttribute("value",k);a.innerHTML=this.getName(a,c,e);return this.setSelected(a,f===k)};c.prototype.getValue=function(a,c,e){c=c[e];if(!(c instanceof Object))return c;e=b.DEFAULT_VALUE_PROPERTY;a.hasAttribute(b.VALUE_BIND_ATTRIBUTE)&&(e=a.getAttribute(b.VALUE_BIND_ATTRIBUTE));
return c[e]};c.prototype.getName=function(a,c,e){c=c[e];if(!(c instanceof Object))return c;e=b.DEFAULT_NAME_PROPERTY;a.hasAttribute(b.NAME_BIND_ATTRIBUTE)&&(e=a.getAttribute(b.NAME_BIND_ATTRIBUTE));return c[e]};c.prototype.setSelected=function(a,b){return b?a.setAttribute("selected",""):a.removeAttribute("selected")};return c}();b=function(b){function a(b){this.element=b;this.valueBind=this.element.getAttribute(a.VALUE_BIND_ATTRIBUTE);this.nameBind=this.element.getAttribute(a.NAME_BIND_ATTRIBUTE);
a.__super__.constructor.call(this,this.element)}e(a,b);a.prototype.calculateItemView=function(){return this.itemView=new f(this)};a.prototype.getExtraModels=function(){return[this.element.getAttribute(a.TO_ATTRIBUTE)]};return a}(BindIt.View.List);b.ItemView=f;b.TO_ATTRIBUTE="to";b.VALUE_BIND_ATTRIBUTE="value-bind";b.NAME_BIND_ATTRIBUTE="name-bind";b.DEFAULT_VALUE_PROPERTY="id";b.DEFAULT_NAME_PROPERTY="name";BindIt.View.SelectSetValue=b}).call(this);
