(function(){window.BindIt={}}).call(this);(function(){BindIt.Logger=console}).call(this);
(function(){var a;a=function(){function a(){this.keys=[];this.values=[];Object.defineProperty(this,"length",{get:function(){return this.keys.length}})}a.prototype.add=function(a,e){var c;c=this.keys.indexOf(a);if(0>c)this.keys.push(a),this.values.push(e);else return this.values[c]=e};a.prototype.remove=function(a){a=this.keys.indexOf(a);if(!(0>a))return this.keys.splice(a,1),this.values.splice(a,1)};a.prototype.clear=function(){this.keys.length=0;return this.values.length=0};a.prototype.get=function(a){a=
this.keys.indexOf(a);return this.values[a]};a.prototype.getKeyByValue=function(a){a=this.values.indexOf(a);return this.keys[a]};a.prototype.length=function(){return this.keys.length};return a}();BindIt.Hash=a}).call(this);
(function(){var a;a=function(){function a(){this.eventHandlers={}}a.prototype.addEventListener=function(a,e){null==this.eventHandlers[a]&&(this.eventHandlers[a]=[]);return this.eventHandlers[a].push(e)};a.prototype.removeEventListener=function(a,e){var c;if(null!=this.eventHandlers[a]&&(c=this.eventHandlers[a].indexOf(e),!(0>c)))return this.eventHandlers[a].splice(c,1)};a.prototype.callEvent=function(a,e){var c,b,d,k,r;if(null!=this.eventHandlers[a]){k=this.eventHandlers[a];r=[];b=0;for(d=k.length;b<
d;b++)c=k[b],r.push(c.apply(this,e));return r}};return a}();window.BindIt.EventDispatcher=a}).call(this);
(function(){var a,f,m,e={}.hasOwnProperty,c=function(b,d){function k(){this.constructor=b}for(var c in d)e.call(d,c)&&(b[c]=d[c]);k.prototype=d.prototype;b.prototype=new k;b.__super__=d.prototype;return b};a=function(b){function d(b,c){var a;this.source=b;null==this.source&&(this.source={});if(this.source instanceof d)return this.source;if(null!=this.source.__bindit_model)return this.source.__bindit_model;if(this.source instanceof Array&&!0!==c)return new BindIt.ModelArray(this.source);d.__super__.constructor.call(this);
Object.defineProperty(this.source,"__bindit_model",{get:function(){return this}.bind(this),enumerable:!1});if(!(this.source instanceof Array))for(a in this.source)m(this,a)}c(d,b);d.prototype.getSource=function(){return this.source};return d}(BindIt.EventDispatcher);f=function(b){return null==b?null:b instanceof Object?new a(b):b};m=function(b,d){if(!b.hasOwnProperty(d))return Object.defineProperty(b,d,{get:function(){var k;k=b.getSource()[d];if(null==k)return null;if(k instanceof Function)return k.bind(b);
k instanceof Object&&(k=new a(k));return k},set:function(k){var c,q;c=b.getSource();q=c[d];k instanceof a&&(k=k.getSource());if(q!==k)return c[d]=k,this.callEvent(a.Events.VALUE_CHANGED,[b,d,f(q),f(k)])},enumerable:!0})};a.processProperty=m;a.Events={VALUE_CHANGED:"value_changed",ARRAY_CHANGED:"array_changed"};window.BindIt.Model=a;window.BindIt.getModel=f;window.BindIt.getSource=function(b){return null==b?null:b instanceof a?b.getSource():b}}).call(this);
(function(){var a,f,m={}.hasOwnProperty,e=function(c,b){function d(){this.constructor=c}for(var k in b)m.call(b,k)&&(c[k]=b[k]);d.prototype=b.prototype;c.prototype=new d;c.__super__=b.prototype;return c};BindIt.Model.ArrayEvents={INSERTED:"inserted",REMOVED:"removed",APOCALYPTIC:"apocalyptic"};a=function(c){function b(d,k){this.source=d;b.__super__.constructor.call(this,this.source,!0);BindIt.Model.processProperty(this,"length");this.source.selectedItem=0;BindIt.Model.processProperty(this,"selectedItem");
null==k&&(k=!0);!0===k&&(this.source.selectedItems=0,BindIt.Model.processProperty(this,"selectedItems"),this.selectedItems=new BindIt.ModelArray([],!1));f(this);this.addEventListener(BindIt.Model.Events.VALUE_CHANGED,function(d,b,k,c){if("length"===b&&!(k>c))return f(d)})}e(b,c);b.prototype.push=function(d){var b;b=this.getSource().push(BindIt.getSource(d));f(this);this.callEvent(BindIt.Model.Events.ARRAY_CHANGED,[this,BindIt.Model.ArrayEvents.INSERTED,this.getSource().length-1,BindIt.getModel(d)]);
return BindIt.getModel(b)};b.prototype.pop=function(){var d;d=this.getSource().pop();this.callEvent(BindIt.Model.Events.ARRAY_CHANGED,[this,BindIt.Model.ArrayEvents.REMOVED,this.getSource().length,BindIt.getModel(d)]);return BindIt.getModel(d)};b.prototype.concat=function(d){return new BindIt.Model(this.getSource().concat(d))};b.prototype.join=function(d){return this.getSource().join(d)};b.prototype.reverse=function(){var d;d=this.getSource().reverse();this.callEvent(BindIt.Model.Events.ARRAY_CHANGED,
[this,BindIt.Model.ArrayEvents.APOCALYPTIC]);return BindIt.getModel(d)};b.prototype.shift=function(){var d;d=this.getSource().shift();this.callEvent(BindIt.Model.Events.ARRAY_CHANGED,[this,BindIt.Model.ArrayEvents.REMOVED,0,BindIt.getModel(d)]);return BindIt.getModel(d)};b.prototype.slice=function(){return new BindIt.Model(this.getSource().slice.apply(this.getSource(),arguments))};b.prototype.sort=function(){var d;d=this.getSource().sort.apply(this.getSource(),arguments);this.callEvent(BindIt.Model.Events.ARRAY_CHANGED,
[this,BindIt.Model.ArrayEvents.APOCALYPTIC]);return BindIt.getModel(d)};b.prototype.splice=function(){var d;d=this.getSource().splice.apply(this.getSource(),arguments);this.callEvent(BindIt.Model.Events.ARRAY_CHANGED,[this,BindIt.Model.ArrayEvents.APOCALYPTIC]);return BindIt.getModel(d)};b.prototype.unshift=function(d){var b;b=this.getSource().unshift(BindIt.getSource(d));this.callEvent(BindIt.Model.Events.ARRAY_CHANGED,[this,BindIt.Model.ArrayEvents.INSERTED,0,BindIt.getModel(d)]);return BindIt.getModel(b)};
b.prototype.indexOf=function(d){return this.getSource().indexOf(BindIt.getSource(d))};return b}(BindIt.Model);f=function(c){var b,d,k,a;a=[];b=d=0;for(k=c.length-1;0<=k?d<=k:d>=k;b=0<=k?++d:--d)a.push(BindIt.Model.processProperty(c,b));return a};window.BindIt.ModelArray=a}).call(this);
(function(){var a,f={}.hasOwnProperty,m=function(a,c){function b(){this.constructor=a}for(var d in c)f.call(c,d)&&(a[d]=c[d]);b.prototype=c.prototype;a.prototype=new b;a.__super__=c.prototype;return a};a=function(a){function c(b){var d=this;this.element=b;c.__super__.constructor.call(this);BindIt.DOM.addEventHandler(this.element,"click",function(){return d.callEvent("click",arguments)})}m(c,a);c.prototype.click=function(b){return this.addEventListener("click",b)};return c}(BindIt.EventDispatcher);
BindIt.DOMEventDispatcher=a}).call(this);
(function(){var a,f=function(c,b){return function(){return c.apply(b,arguments)}},m={}.hasOwnProperty,e=function(c,b){function d(){this.constructor=c}for(var k in b)m.call(b,k)&&(c[k]=b[k]);d.prototype=b.prototype;c.prototype=new d;c.__super__=b.prototype;return c};BindIt.DATA_BIND_ATTRIBUTE="data-bind";BindIt.FORM_BIND_ATTRIBUTE="form-bind";a=function(c){function b(d){this.element=d;this.modelArrayHandler=f(this.modelArrayHandler,this);this.modelHandler=f(this.modelHandler,this);if(null!=this.element.__bindit_view)throw Error("Element should have only one view");
b.__super__.constructor.call(this,this.element);d.__bindit_view=this;this.subscribes=[];this.refreshSubscribes()}e(b,c);b.prototype.getValue=function(d,b){var c;null==b&&(b=this.getModelPath());if(null==b||0===b.length)return null;try{c=eval(b.shift())}catch(a){}for(;0<b.length;){if(null==c)return null;c instanceof BindIt.ModelArray&&(c=c[c.selectedItem]);null!=c&&(c=c[b.shift()])}c instanceof BindIt.ModelArray&&!0!==d&&(c=c[c.selectedItem]);return c};b.prototype.setValue=function(d,b){var c,a;c=
b;null==b&&(c=this.getModelPath());null==c&&(c=[]);for(a=window;1<c.length;){if(null==a)return;a instanceof BindIt.ModelArray&&(a=a[a.selectedItem]);if(null==a)return;a=a[c.shift()]}if(null!=a&&(a instanceof BindIt.ModelArray&&(a=a[a.selectedItem]),null!=a))return a[c[0]]=d};b.prototype.callBindFunction=function(){var d,b,c;b=this.getModelPath();null==b&&(b=[]);c=null;for(d=window;0<b.length&&null!=d;){d instanceof BindIt.ModelArray&&(c=d,d=d[d.selectedItem]);if(null==d)break;c=d;d=d[b.shift()]}if(null!=
d&&d instanceof Function)return d.apply(c,arguments)};b.prototype.getModelPath=function(d){var b,c,a,n;null==d&&(d=this.element.getAttribute(BindIt.DATA_BIND_ATTRIBUTE));if(null==d)return null;b=this.element.parentNode;if(":"!==d[0])for(;null!==b;)null!=b.hasAttribute&&b.hasAttribute(BindIt.FORM_BIND_ATTRIBUTE)&&(d=""+b.getAttribute(BindIt.FORM_BIND_ATTRIBUTE)+":"+d),b=b.parentNode;c=d.split(":");b=[];a=0;for(n=c.length;a<n;a++)d=c[a],null!=d&&""!==d&&b.push(d);return b};b.prototype.modelHandler=
function(d,b,c,a){this.refreshSubscribes();return"function"===typeof this.changed?this.changed(this,d,BindIt.Model.Events.VALUE_CHANGED,b,c,a):void 0};b.prototype.modelArrayHandler=function(d,b,c,a){this.refreshSubscribes();return"function"===typeof this.changed?this.changed(this,d,BindIt.Model.Events.ARRAY_CHANGED,b,c,a):void 0};b.prototype.refreshSubscribes=function(){var d,b,c,a,n,g,e;c=[];c.push(this.getModelPath());b=this.getExtraModels();if(null!=b)for(a=0,n=b.length;a<n;a++)d=b[a],d=this.getModelPath(d),
null!=d&&c.push(d);b=[];d=0;for(g=c.length;d<g;d++){n=c[d];null==n&&(n=[]);for(a=window;0<n.length&&null!=a;){a instanceof BindIt.ModelArray&&(a=a[a.selectedItem],a instanceof BindIt.Model&&b.push(a));if(null==a)break;a=a[n.shift()];a instanceof BindIt.Model&&b.push(a)}this.fillSubscribes(a,b,!1)}a=[];n=[];d=0;for(g=b.length;d<g;d++)c=b[d],0>this.subscribes.indexOf(c)&&n.push(c);e=this.subscribes;d=0;for(g=e.length;d<g;d++)c=e[d],0>b.indexOf(c)&&a.push(c);g=0;for(d=n.length;g<d;g++)c=n[g],c.addEventListener(BindIt.Model.Events.VALUE_CHANGED,
this.modelHandler),c instanceof BindIt.ModelArray&&c.addEventListener(BindIt.Model.Events.ARRAY_CHANGED,this.modelArrayHandler);d=0;for(n=a.length;d<n;d++)c=a[d],c.removeEventListener(BindIt.Model.Events.VALUE_CHANGED,this.modelHandler),c instanceof BindIt.ModelArray&&c.removeEventListener(BindIt.Model.Events.ARRAY_CHANGED,this.modelArrayHandler);return this.subscribes=b};b.prototype.fillSubscribes=function(d,b,c){var a,n;if(null!=d&&d instanceof BindIt.Model&&!(0<=b.indexOf(d)&&c))if(0>b.indexOf(d)&&
b.push(d),d instanceof BindIt.ModelArray)for(this.fillSubscribes(d.selectedItems,b,!0),c=0,n=d.length;c<n;c++)a=d[c],this.fillSubscribes(a,b,!0);else{c=[];for(a in d)c.push(this.fillSubscribes(d[a],b,!0));return c}};b.prototype.getExtraModels=function(){return null};return b}(BindIt.DOMEventDispatcher);BindIt.View=a}).call(this);
(function(){var a,f,m,e;BindIt.VIEW_ATTRIBUTE="view";f=function(c){var b;b=c.getAttribute(BindIt.VIEW_ATTRIBUTE);null==b&&(b=BindIt.View.Default[c.tagName.toLowerCase()]);null==b&&(b="BindIt.View");c=BindIt.View;try{c=eval(b)}catch(d){}return c};a=function(c){var b;if(null!=c&&(null==c.__bindit_view&&null!=c.getAttribute)&&(b=c.getAttribute(BindIt.DATA_BIND_ATTRIBUTE),null!=b))return new (f(c))(c)};e=function(c){var b,d,k,r;a(c);if(null!=c.getElementsByTagName){b=c.getElementsByTagName("*");r=[];
d=0;for(k=b.length;d<k;d++)c=b[d],r.push(a(c));return r}};BindIt.DOM={getViewClass:f,createView:a,processElement:e,addEventHandler:function(c,b,d){if(null!=d&&null!=c.addEventListener)return c.addEventListener(b,d)}};BindIt.View.Default={};m=function(){return e(document)};(function(){BindIt.DOM.addEventHandler(window,"load",m);return BindIt.DOM.addEventHandler(window,"DOMSubtreeModified",function(c){return e(c.target)})})()}).call(this);
(function(){var a,f,m,e,c,b=function(d,b){return function(){return d.apply(b,arguments)}};a=function(){function d(c){this.template=c;this.create=b(this.create,this);if(this.template instanceof d)return this.template}d.prototype.create=function(){var d;d=c(this,this.template.tag,arguments);d=null!=d?document.createElement(d):document.createDocumentFragment();m(this,d,arguments);e(this,d,arguments);return d};return d}();m=function(d,b,r){var q,n,g,e,f;n=d.template.attributes;null==n&&(n={});n=c(d,n,
r);f=a.OftenAttributes;g=0;for(e=f.length;g<e;g++)q=f[g],null!=d.template[q]&&(n[q]=d.template[q]);g=[];for(q in n)d=n[q],d=c(this,d,r),g.push(b.setAttribute(q,d));return g};e=function(d,b,a){var q,n,e,l,p;n=c(d,d.template.html,a);e=c(d,d.template.text,a);q=c(d,d.template.child,a);if(1<(null!=n?1:0)+(null!=e?1:0)+(null!=q?1:0))throw Error("Template exception. Only one available: html, text, child");null!=n&&(b.innerHTML=n);null!=e&&(b.innerText=e);if(null!=q){p=[];e=0;for(l=q.length;e<l;e++)n=q[e],
p.push(f(d,b,n,a));return p}};f=function(d,b,c,q){var e,g;e=c;e instanceof Function&&(e=e.apply(d,q));if("string"===typeof e)return b.appendChild(document.createTextNode(e));if(e instanceof Node&&(null!=c[a.TEMPLATE_ID_PROPERTY]&&(b[c[a.TEMPLATE_ID_PROPERTY]]=c),e instanceof Node))return b.appendChild(c);if(e instanceof Object)return d=new a(e),null!=d[a.TEMPLATE_ID_PROPERTY]&&(g=d[a.TEMPLATE_ID_PROPERTY]),null!=d.template[a.TEMPLATE_ID_PROPERTY]&&null==g&&(g=d.template[a.TEMPLATE_ID_PROPERTY]),q=
d.create.apply(e,q),null!=g&&(b[g]=q),b.appendChild(q)};c=function(d,b,c){var a;a=b;b instanceof Function&&(a=b.apply(d,c));return a};a.OftenAttributes=["id","name","class","style","src","href","value",BindIt.DATA_BIND_ATTRIBUTE,BindIt.VIEW_ATTRIBUTE,"item-view","type","form-bind"];a.TEMPLATE_ID_PROPERTY="template-id";BindIt.Template=a}).call(this);
(function(){var a,f,m={}.hasOwnProperty,e=function(c,b){function d(){this.constructor=c}for(var a in b)m.call(b,a)&&(c[a]=b[a]);d.prototype=b.prototype;c.prototype=new d;c.__super__=b.prototype;return c};a=function(c){function b(d){var c;this.element=d;b.__super__.constructor.call(this,this.element);this.itemsSubscribes=new BindIt.Hash;this.itemsElements=[];this.calculateItemView();null!=this.itemView&&("function"===typeof(c=this.itemView).init&&c.init(this),this.changed())}e(b,c);b.prototype.changed=
function(d,b,c,a,e,g){this.callChanged(b,c,c===BindIt.Model.Events.VALUE_CHANGED?null:a,c===BindIt.Model.Events.VALUE_CHANGED?null:e,c===BindIt.Model.Events.VALUE_CHANGED?a:null,c===BindIt.Model.Events.VALUE_CHANGED?e:null,g);return this.refreshItemsSubscribes()};b.prototype.callChanged=function(d,b,c,a,e,g,l){var p,m,h;h=this.getValue(!0);if(null!=h){p=this.itemsSubscribes.get(d);c!==BindIt.Model.ArrayEvents.INSERTED&&c!==BindIt.Model.ArrayEvents.REMOVED&&(a=h.indexOf(p));m=this.itemsElements[a];
if(null!=p&&null!=m&&(a=h.indexOf(p),null!=p&&null!=m))return this.itemView.changed(m,h,a,h.selectedItem===a,0<=h.selectedItems.indexOf(a));if(d===h&&b===BindIt.Model.Events.VALUE_CHANGED){if("length"===e){if(g<l)for(a=h=g,p=l-1;g<=p?h<=p:h>=p;a=g<=p?++h:--h)l=this.createItemElement(d,a),null!=l&&this.element.appendChild(l);else{for(;null!=this.element.childNodes[l];)h=this.element.childNodes[this.element.childNodes.length-1],this.element.removeChild(h);this.itemsElements.length=l}return}if("selectedItem"===
e){this.itemView.changed(this.itemsElements[g],h,g,!1,0<=h.selectedItems.indexOf(g));this.itemView.changed(this.itemsElements[l],h,l,!0,0<=h.selectedItems.indexOf(g));return}if("selectedItems"===e){d=[];a=0;for(b=g.length;a<b;a++)p=g[a],d.push(p);a=0;for(g=l.length;a<g;a++)p=l[a],d.push(p);if(0<d.length)for(a=l=0,d=d.length-1;0<=d?l<=d:l>=d;a=0<=d?++l:--l)this.itemView.changed(this.itemsElements[a],h,a,a===h.selectedItem,0<=h.selectedItems.indexOf(a));return}if(f(e)&&(a=parseInt(e),m=this.itemsElements[a],
null!=l&&null!=m))return this.itemView.changed(m,h,a,h.selectedItem===a,0<=h.selectedItems.indexOf(a))}if(d===h.selectedItems){if(c===BindIt.Model.ArrayEvents.INSERTED){m=this.itemsElements[l];this.itemView.changed(m,h,l,h.selectedItem===l,0<=h.selectedItems.indexOf(l));return}if(c===BindIt.Model.ArrayEvents.REMOVED){m=this.itemsElements[l];this.itemView.changed(m,h,l,h.selectedItem===l,0<=h.selectedItems.indexOf(l));return}if(b===BindIt.Model.Events.VALUE_CHANGED&&f(e)){this.itemView.changed(this.itemsElements[g],
h,g,h.selectedItem===g,0<=h.selectedItems.indexOf(g));this.itemView.changed(this.itemsElements[l],h,l,h.selectedItem===l,0<=h.selectedItems.indexOf(l));return}}if(d===h&&c===BindIt.Model.ArrayEvents.INSERTED){l=this.createItemElement(d,a);if(null==l)return;if(h.length>a+1)for(g=p=b=a+1,c=h.length-1;b<=c?p<=c:p>=c;g=b<=c?++p:--p)this.itemView.changed(this.itemsElements[g],h,g,h.selectedItem===g,0<=h.selectedItems.indexOf(g));return a===d.length-1?this.element.appendChild(l):this.element.insertBefore(l,
this.element.childNodes[a])}if(d===h&&c===BindIt.Model.ArrayEvents.REMOVED){this.itemsElements.splice(a,1);if(h.length>a)for(g=d=l=a,p=h.length-1;l<=p?d<=p:d>=p;g=l<=p?++d:--d)this.itemView.changed(this.itemsElements[g],h,g,h.selectedItem===g,0<=h.selectedItems.indexOf(g));return this.element.removeChild(this.element.childNodes[a])}return this.apocalyptic()}};b.prototype.calculateItemView=function(){var d;if(this.element.hasAttribute(b.ITEM_VIEW_ATTRIBUTE)){d=this.element.getAttribute(b.ITEM_VIEW_ATTRIBUTE);
try{this.itemView=eval(d)}catch(c){BindIt.Logger.warn("BindIt.View.ListView: invalid '"+b.ITEM_VIEW_ATTRIBUTE+"' attribute",this.element);return}if(null==this.itemView)return BindIt.Logger.warn("BindIt.View.ListView: invalid '"+b.ITEM_VIEW_ATTRIBUTE+"' attribute",this.element)}else BindIt.Logger.warn("BindIt.View.ListView: element hasn't '"+b.ITEM_VIEW_ATTRIBUTE+"' attribute",this.element)};b.prototype.apocalyptic=function(){for(var d,b,c,a,e;null!=this.element.firstChild;)this.element.removeChild(this.element.firstChild);
this.itemsElements=[];c=this.getValue(!0);if(null!=c){b=document.createDocumentFragment();if(0<c.length)for(d=a=0,e=c.length-1;0<=e?a<=e:a>=e;d=0<=e?++a:--a)d=this.createItemElement(c,d),null!=d&&b.appendChild(d);return this.element.appendChild(b)}};b.prototype.createItemElement=function(d,b){var c;if(null!=this.itemView)return c=this.itemView.create(d,b,d.selectedItem===b,0<=d.selectedItems.indexOf(b)),this.itemsElements.splice(b,0,c),c};b.prototype.refreshItemsSubscribes=function(){var b,c,a,e,
f,g,l;e=this.getValue(!0);if(null!=e){this.itemsSubscribes.clear();l=[];f=0;for(g=e.length;f<g;f++)b=e[f],null!=b?(a=[],this.fillSubscribes(b,a,!0),l.push(function(){var e,g,f;f=[];e=0;for(g=a.length;e<g;e++)c=a[e],f.push(this.itemsSubscribes.add(c,b));return f}.call(this))):l.push(void 0);return l}};return b}(BindIt.View);f=function(c){return parseInt(c)===c};a.ITEM_VIEW_ATTRIBUTE="item-view";BindIt.View.List=a}).call(this);
(function(){var a,f={}.hasOwnProperty,m=function(a,c){function b(){this.constructor=a}for(var d in c)f.call(c,d)&&(a[d]=c[d]);b.prototype=c.prototype;a.prototype=new b;a.__super__=c.prototype;return a};a=function(a){function c(b){var d;this.element=b;d=this.element.getAttribute("type")||"undefined";b=c.byType[d.toLowerCase()];if(null!=b&&b instanceof Function)return new b(this.element);BindIt.Logger.warn("Can't find view class for input tag with type '"+d+"'",this.element)}m(c,a);return c}(BindIt.View);
a.byType={};BindIt.View.Input=a;BindIt.View.Default.input=a}).call(this);
(function(){var a,f={}.hasOwnProperty,m=function(a,c){function b(){this.constructor=a}for(var d in c)f.call(c,d)&&(a[d]=c[d]);b.prototype=c.prototype;a.prototype=new b;a.__super__=c.prototype;return a};a=function(a){function c(b){var d=this;this.element=b;c.__super__.constructor.call(this,this.element);this.setEnabled(this.getValue(!1));this.click(function(){var b;b=d.getValue(!1);if(d.getEnabled(b)){if(b instanceof Function)return d.callBindFunction();if(b.call instanceof Function)return b.call.apply(b)}})}
m(c,a);c.prototype.changed=function(){return this.setEnabled(this.getValue(!1))};c.prototype.setEnabled=function(b){return this.getEnabled(b)?this.element.removeAttribute("disabled"):this.element.setAttribute("disabled","disabled")};c.prototype.getEnabled=function(b){var d;if(null===b)return!1;if(b instanceof Function)return!0;b instanceof Object&&(d=b.enabled);d instanceof Function&&(d=d.apply(b));return!0===d&&(b instanceof Function||b.call instanceof Function)};return c}(BindIt.View);BindIt.View.Button=
a;BindIt.View.Default.button=a;BindIt.View.Default.a=a;BindIt.View.Input.byType.button=a}).call(this);
(function(){var a,f=function(c,b){return function(){return c.apply(b,arguments)}},m={}.hasOwnProperty,e=function(c,b){function d(){this.constructor=c}for(var a in b)m.call(b,a)&&(c[a]=b[a]);d.prototype=b.prototype;c.prototype=new d;c.__super__=b.prototype;return c};a=function(a){function b(d){this.element=d;this.calculateEvent=f(this.calculateEvent,this);this.elementListener=f(this.elementListener,this);this.keyup=f(this.keyup,this);b.__super__.constructor.call(this,this.element);this.changed();this.calculateEvent("enter");
this.calculateEvent("esc");this.element.onchange=this.elementListener;this.element.onkeyup=this.keyup;this.element.onpaste=this.elementListener}e(b,a);b.prototype.changed=function(){this.setEnabled();return this.setElementValue(this.getValue())};b.prototype.setEnabled=function(){return null!=this.getValue()?this.element.removeAttribute("disabled"):this.element.setAttribute("disabled","disabled")};b.prototype.setElementValue=function(b){b=b||"";if(this.element.value!==b)return this.element.value=b};
b.prototype.keyup=function(b){this.elementListener();13===b.keyCode&&"function"===typeof this.enter&&this.enter(b);if(27===b.keyCode)return"function"===typeof this.esc?this.esc(b):void 0};b.prototype.elementListener=function(){if(this.element.value!==this.getValue())return this.setValue(this.element.value)};b.prototype.calculateEvent=function(b){var a,c,e,f,g=this;if(this.element.hasAttribute(b)){f=this.element.getAttribute(b);a=f.lastIndexOf(".");a=0>a?"window":a=f.substr(0,a);try{return c=eval(f),
e=eval(a),this[b]=function(b){if(null!=c&&c instanceof Function)return c.apply(e,[g,b])}}catch(l){}}};return b}(BindIt.View);BindIt.View.Text=a;BindIt.View.Default.textarea=a;BindIt.View.Input.byType.text=a;BindIt.View.Input.byType.password=a;BindIt.View.Input.byType.hidden=a;BindIt.View.Input.byType.email=a;BindIt.View.Input.byType.search=a;BindIt.View.Input.byType.tel=a;BindIt.View.Input.byType.color=a;BindIt.View.Input.byType.range=a;BindIt.View.Input.byType.number=a;BindIt.View.Input.byType.url=
a;BindIt.View.Input.byType.time=a;BindIt.View.Input.byType.month=a;BindIt.View.Input.byType.week=a;BindIt.View.Input.byType.date=a;BindIt.View.Input.byType.datetime=a;BindIt.View.Input.byType["datetime-local"]=a}).call(this);
(function(){var a,f={}.hasOwnProperty,m=function(a,c){function b(){this.constructor=a}for(var d in c)f.call(c,d)&&(a[d]=c[d]);b.prototype=c.prototype;a.prototype=new b;a.__super__=c.prototype;return a};a=function(a){function c(b){c.__super__.constructor.call(this,b);this.subscribe();this.changed()}m(c,a);c.prototype.changed=function(){this.setElementValue(!0===this.getValue());return this.setElementEnabled(!0===this.getValue()||!1===this.getValue())};c.prototype.subscribe=function(){var b=this;return this.element.onchange=
function(){return b.setValue(b.getElementValue())}};c.prototype.getElementValue=function(){return this.element.checked};c.prototype.setElementValue=function(b){return this.element.checked=b};c.prototype.setElementEnabled=function(b){return b?this.element.removeAttribute("disabled"):this.element.setAttribute("disabled","")};return c}(BindIt.View);BindIt.View.Checkbox=a;BindIt.View.Input.byType.checkbox=a}).call(this);
(function(){var a,f,m={}.hasOwnProperty,e=function(a,b){function d(){this.constructor=a}for(var e in b)m.call(b,e)&&(a[e]=b[e]);d.prototype=b.prototype;a.prototype=new d;a.__super__=b.prototype;return a};f=function(){function a(){}a.prototype.init=function(b){return b.element.onchange=function(){var a;a=b.getValue(!0);if(null!=a)return a.selectedItem=parseInt(b.element.value)}};a.prototype.create=function(b,a,c){var e;e=document.createElement("option");e.innerHTML=b[a];e.setAttribute("value",a);this.setSelected(e,
b,a,c);return e};a.prototype.changed=function(b,a,c,e){b.innerHTML=a[c];return this.setSelected(b,a,c,e)};a.prototype.setSelected=function(b,a,c,e){return e?b.setAttribute("selected",""):b.removeAttribute("selected")};return a}();f.instance=new f;a=function(a){function b(a){this.element=a;b.__super__.constructor.call(this,this.element)}e(b,a);b.prototype.calculateItemView=function(){return this.itemView=f.instance};return b}(BindIt.View.List);a.ItemView=f;BindIt.View.Select=a;BindIt.View.Default.select=
a}).call(this);
(function(){var a,f={}.hasOwnProperty,m=function(a,c){function b(){this.constructor=a}for(var d in c)f.call(c,d)&&(a[d]=c[d]);b.prototype=c.prototype;a.prototype=new b;a.__super__=c.prototype;return a};a=function(a){function c(b){var a=this;this.element=b;c.__super__.constructor.call(this,this.element);this.element.onchange=function(){return a.setValue(a.element.getAttribute(c.VALUE_ATTRIBUTE))};this.changed()}m(c,a);c.prototype.changed=function(){var b,a;a=this.getValue(!1);b=this.element.getAttribute(c.VALUE_ATTRIBUTE);this.setElementEnabled(null!=
a);return this.setElementChecked(a===b)};c.prototype.setElementEnabled=function(b){return b?this.element.removeAttribute("disabled"):this.element.setAttribute("disabled","")};c.prototype.setElementChecked=function(b){return b?this.element.setAttribute("checked",""):this.element.removeAttribute("checked")};return c}(BindIt.View);a.VALUE_ATTRIBUTE="value";BindIt.View.Radio=a;BindIt.View.Input.byType.radio=a}).call(this);
(function(){var a,f,m={}.hasOwnProperty,e=function(a,b){function d(){this.constructor=a}for(var e in b)m.call(b,e)&&(a[e]=b[e]);d.prototype=b.prototype;a.prototype=new d;a.__super__=b.prototype;return a};f=function(){function c(b){this.view=b}c.prototype.init=function(b){return b.element.onchange=function(){var d;d=b.element.value;if(null!=d)return b.setValue(d,b.getModelPath(b.element.getAttribute(a.TO_ATTRIBUTE)))}};c.prototype.create=function(b,a){var c;c=document.createElement("option");this.initElement(c,
b,a);return c};c.prototype.changed=function(b,a,c,e){return this.initElement(b,a,c)};c.prototype.initElement=function(b,d,c){var e,f;try{e=this.view.getValue(!1,this.view.getModelPath(this.view.element.getAttribute(a.TO_ATTRIBUTE)))}catch(m){}f=this.getValue(b,d,c);b.setAttribute("value",f);b.innerHTML=this.getName(b,d,c);return this.setSelected(b,e===f)};c.prototype.getValue=function(b,d,c){d=d[c];if(!(d instanceof Object))return d;c=a.DEFAULT_VALUE_PROPERTY;b.hasAttribute(a.VALUE_BIND_ATTRIBUTE)&&
(c=b.getAttribute(a.VALUE_BIND_ATTRIBUTE));return d[c]};c.prototype.getName=function(b,c,e){c=c[e];if(!(c instanceof Object))return c;e=a.DEFAULT_NAME_PROPERTY;b.hasAttribute(a.NAME_BIND_ATTRIBUTE)&&(e=b.getAttribute(a.NAME_BIND_ATTRIBUTE));return c[e]};c.prototype.setSelected=function(b,a){return a?b.setAttribute("selected",""):b.removeAttribute("selected")};return c}();a=function(a){function b(a){this.element=a;this.valueBind=this.element.getAttribute(b.VALUE_BIND_ATTRIBUTE);this.nameBind=this.element.getAttribute(b.NAME_BIND_ATTRIBUTE);
b.__super__.constructor.call(this,this.element)}e(b,a);b.prototype.calculateItemView=function(){return this.itemView=new f(this)};b.prototype.getExtraModels=function(){return[this.element.getAttribute(b.TO_ATTRIBUTE)]};return b}(BindIt.View.List);a.ItemView=f;a.TO_ATTRIBUTE="to";a.VALUE_BIND_ATTRIBUTE="value-bind";a.NAME_BIND_ATTRIBUTE="name-bind";a.DEFAULT_VALUE_PROPERTY="id";a.DEFAULT_NAME_PROPERTY="name";BindIt.View.SelectSetValue=a}).call(this);
